### ISSUE TITLE
Output generated in the output tab moves cursor focus to the output tab.

### ISSUE THREAD

**Issue by BradLewis** [tim-koehler/Helm-Intellisense#15]
So that's not the clearest title so I'll try to explain what I mean by that.

When typing a command, the intellisense all works correctly and as expected, however after typing .Values. (after typing the last dot), the intellisense appears as expected (and lists all of my available values), however after around a second, a message appears in the output:

> Missing value at path [.Values.] in file [{PATH}\deployment.yaml:16]

Whilst this error appearing in the output isn't an issue exactly, it forces the focus from the window where I am typing to the output window making it very difficult to type anything.

**Comment by tim-koehler** [comment]
Hey @BradLewis 
this is strange...do you have some kind of autosave plugin installed? The linter should only be running when the document is saved or you execute the command manually.

If you dont't want the linter to be activated when the file is saved you can do the following in your `settings.json`:
`"helm-intellisense.lintFileOnSave": false,`

**Comment by BradLewis** [comment]
Hi Tim, 
Yeah that's it! I use the autosaving feature which runs after a second of not typing which was running the linter. Disabling the linting on save fixes this.
However it be possible to stop the output changing the window focus?

**Comment by tim-koehler** [comment]
Yep already working on that :)

**Comment by tim-koehler** [comment]
Fix released with v0.7.4
