### ISSUE TITLE
Enhancement proposal - Show actual resolved values

### ISSUE THREAD

**Issue by TalZiv** [tim-koehler/Helm-Intellisense#18]
Hi,

Great plugin, really helps out in writing templates.
Would it be possible to show the actual value from Values.yaml?

example:
{{ .Values.global.services.docker_registry_port }}

to show the actual port number in some form, preferred way would be in the intellisense pop-up or maybe right click?

Thanks,
Tal

**Comment by tim-koehler** [comment]
Hey @TalZiv,
glad you like my work :relaxed: 

This value preview feature is already part of the extension as you can see here
![Example](https://user-images.githubusercontent.com/27742321/92454559-ebc82a00-f1c0-11ea-91fc-59e8af34081d.png)
You may have to click on a little arrow on the suggestion to see the value

**Comment by TalZiv** [comment]
Thank you for the quick reply, I missed the small ">" by the property name  or ctrl+space that extends and shows the content of the value
![image](https://user-images.githubusercontent.com/22313897/92458857-a0b51380-f1ce-11ea-8d67-3cb72aac062b.png)

Again thank you!
