### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MarcelRaschke** [tim-koehler/Helm-Intellisense#19]
- Issue Type: `Performance`
- Extension Name: `helm-intellisense`
- Extension Version: `0.7.7`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.50.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Melon\AppData\Local\Temp\Tim-Koehler.helm-intellisense-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by tim-koehler** [comment]
Hey Marcel,
I am not able to reproduce that. There is no file beeing generated on my machine.
Can you upload yours?
