### ISSUE TITLE
auto completion is not fetching values from _helpers.tpl

### ISSUE THREAD

**Issue by sakthimaan** [tim-koehler/Helm-Intellisense#23]
auto completion is not working for values present in the _helpers.tpl. 

*_helpers.tpl*
```
{{- define "nginx.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}


```
**Example :** 
_Completion from Pycharm Professional._

![image](https://user-images.githubusercontent.com/14888257/100578963-504edd00-3309-11eb-9e9a-0d53b6dc61a8.png)

**Comment by tim-koehler** [comment]
I will look into this as soon as I find some time :blush:

**Comment by tim-koehler** [comment]
@sakthimaan Added with release v0.8.0 :blush:
