### ISSUE TITLE
Missing value at path rule should be improved

### ISSUE THREAD

**Issue by xrow** [tim-koehler/Helm-Intellisense#27]
First off... thanks for this idea/tool. I am currently testing, if it is helpfull. I noticed the following when usign it with my charts:

In this example you see the the tool is generating an error. This is indeed correct that .Values.externalServices.mysql is not existing, but at the same time it is my desire to have the default empty. That is the reason why im am testing for the value.

Futhermore I do not know what to recommend. I just wanted to let you know.

![image](https://user-images.githubusercontent.com/295491/106797524-0366ea00-665d-11eb-9c96-242d1b822662.png)

**Comment by tim-koehler** [comment]
Hey @xrow, thanks for informing me about this. I adjusted the regex for the Linter to not only ignore the `{{ if...` but also the `{{ else if...` lines. I plan on introducing an option in the settings to enable/disable linting for those if/else conditions. For now the Linter will just ignore these.

**Comment by tim-koehler** [comment]
Fix released with v0.9.1
