### ISSUE TITLE
Limit suggestions to go template actions

### ISSUE THREAD

**Issue by marcfrederick** [tim-koehler/Helm-Intellisense#3]
Currently completions will be suggested outside of go template actions. They should be limited to the inside of the curly brackets.

**Comment by tim-koehler** [comment]
Fixed with v0.1.2

**Comment by marcfrederick** [comment]
This is still kind of broken as it simply looks for opening curly braces before and closing ones after the current cursor position. Something like the following still leads to completions:
```yaml
{{  }} .Values.… {{  }}
```

**Comment by marcfrederick** [comment]
> This is still kind of broken as it simply looks for opening curly braces before and closing ones after the current cursor position. Something like the following still leads to completions:
> 
> ```yaml
> {{  }} .Values.… {{  }}
> ```

Fixed suggested in #7
