### ISSUE TITLE
Option to suppress notification

### ISSUE THREAD

**Issue by jsbrain** [tim-koehler/Helm-Intellisense#33]
There should be an option to disable the "Give a Start on GitHub" notification each time one starts VS Code 🙂

**Comment by jsbrain** [comment]
Grüße aus Ravensburg 🥳

**Comment by tim-koehler** [comment]
The notification is only appearing once every 50 startups. It is not intended to get that popup every time. This should also be the case for you. I can't explain why this is coming up every time on your setup.

Anyways I disabled the notification completely with the recent update after you clicked the "Give a Start" button once.

Liebe Grüße zurrück aus Konstanz 😊
