### ISSUE TITLE
Specify Hierarchy of Value Files

### ISSUE THREAD

**Issue by grant-zietsman** [tim-koehler/Helm-Intellisense#35]
This is more of a question than an issue?

## Hierarchy Support 

Are there any plans to support specifying a hierarchy of value files. For example one representation could be:

```js
customValueFileNames = [
  // default values
  "values.yaml",
  // staging-values which inherits from values
  ["staging-values.yaml", "values.yaml"],
  // production-values inherit from staging which inherit from values
  ["production-values.yaml", "staging-values.yaml", "values.yaml"],
]
```

At least in my current use case it seems quite handy to be able to check hierarchies of template values.

## Checking All Values

I also noticed that `customValueFileNames` uses the first found value file. Are there any plans to check all specified value files, if found?

**Comment by tim-koehler** [comment]
Hey @grant-zietsman,
this hierarchy support thing is something I already thought about. And now after seeing that it would add value for others I will look into it as soon as I find some time :)

**Comment by grant-zietsman** [comment]
Thanks @tim-koehler, that would be fantastic!

**Comment by tim-koehler** [comment]
Hey @grant-zietsman,
this should now work 👍🏼 

Check the extension description/readme for the exact config.

**Comment by grant-zietsman** [comment]
Thanks @tim-koehler, that was fast. I'll try it out!
