### ISSUE TITLE
lint should ignore Annotations strings

### ISSUE THREAD

**Issue by ciiiii** [tim-koehler/Helm-Intellisense#47]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/28784251/142992546-3a896fd7-8df5-4816-805b-7d65b1e2f353.png">

**Comment by marcfrederick** [comment]
Hey @ciiiii, could you specify what you mean by annotation strings? It's unclear to me from your screenshot in what context this occurs. Do you mean inside template comments (`{{ /* ... */ }}`)?

**Comment by ciiiii** [comment]
Yes, lint should ignore Field in comments. @marcfrederick

**Comment by d1820** [comment]
It should also allow valid usages in a :set call

![image](https://user-images.githubusercontent.com/377631/164513252-b1475d5d-0a5f-4cc8-b4ea-467a47aabc73.png)

**Comment by tim-koehler** [comment]
Hey @ciiiii 
i know it took some time but I just released a patch for the linter to ignore when inside comments.

**Comment by ciiiii** [comment]
> Hey @ciiiii 
> 
> i know it took some time but I just released a patch for the linter to ignore when inside comments.

That's awesome, I can't wait to upgrade it.

**Comment by SayLaVie** [comment]
@tim-koehler This fix only works for single-line comments, right? Could you also apply it to mult-line comments?
