### ISSUE TITLE
Ignore `README.md.gotmpl`

### ISSUE THREAD

**Issue by AndersBennedsgaard** [tim-koehler/Helm-Intellisense#50]
Thank you very much for this extension, it has already helped out with several bugs so far :smile: 

I just have a small issue for now: when using [helm-docs](https://github.com/norwoodj/helm-docs), you often write a `README.md.gotmpl` next to a chart `README.md`. 
This file can look something like this:
```
{{ template "chart.header" . }}
{{ template "chart.deprecationWarning" . }}
{{ template "chart.badgesSection" . }}
{{ template "chart.description" . }}
{{ template "chart.valuesSection" . }}
```

Each of the `template`s are catched with the message `Template not defined`.
Would it be possible to ignore specific files such as these?

**Comment by tim-koehler** [comment]
Hey @AndersBennedsgaard
Thanks a lot for your feedback!
I will find a solution for your problem within the next days ☺️ 

\- Tim

**Comment by AndersBennedsgaard** [comment]
That sounds great, thanks! 

It would be very nice if it was possible for users to create a list of ignored files through VSCode settings where this file is included by default, but that should probably be included in a new issue?

**Comment by tim-koehler** [comment]
@AndersBennedsgaard I just released `v0.14.0` which includes a setting called `helm-intellisense.excludeFromLinting`. There you can add all filenames (only filename without path) which should be excluded from linting.

Let me know if this works for you. 

\- Tim

**Comment by AndersBennedsgaard** [comment]
Oh, sorry I haven't gotten back to you. I haven't had the time to test it, but it sounds like a good solution 👍 
Is it possible to use wildcards, such that we could use `*.gotmpl` to catch others?

**Comment by tim-koehler** [comment]
Yep that is possible 👍🏼
