### ISSUE TITLE
Syntax checking should ignore comments

### ISSUE THREAD

**Issue by KagurazakaNyaa** [tim-koehler/Helm-Intellisense#54]
https://github.com/prometheus-community/helm-charts/blob/5c6f26588c0815d53cbc2ec68e8626b7bef69a41/charts/kube-prometheus-stack/values.yaml#L210
will report "Template not defined"

https://github.com/prometheus-community/helm-charts/blob/5c6f26588c0815d53cbc2ec68e8626b7bef69a41/charts/kube-prometheus-stack/values.yaml#L2512
will report "Value not defined"

But these codes start with #, indicating that they are a comment and should not be checked for syntax.

**Comment by tim-koehler** [comment]
Hey @KagurazakaNyaa 
Thanks for reporting that bug. `values.yaml` should not be linted at all!
This is fixed now.
