### ISSUE TITLE
kubernetes autocompletion on helm-templates

### ISSUE THREAD

**Issue by Torkolis** [tim-koehler/Helm-Intellisense#57]
Hi,
I have an issue where kubernetes autocompletion does not work when I write a helm chart.
![image](https://user-images.githubusercontent.com/98939160/176670727-a3efb296-cdd8-4247-8722-f1edec180859.png)
while the same does work if not helm-template
![image](https://user-images.githubusercontent.com/98939160/176670798-e9476f87-4165-4154-a397-4bee1585ebad.png)
Is there a way to enable it?

**Comment by tim-koehler** [comment]
This is not related to Helm-Intellisense. The suggestions you see there are from the kubernetes extension.
