### ISSUE TITLE
Please stop asking me to star this project on GitHub

### ISSUE THREAD

**Issue by KTamas** [tim-koehler/Helm-Intellisense#59]
This has been popping up every day for more than a week now. At this point, I'm considering forking the project to remove this single feature.

**Comment by tim-koehler** [comment]
Hey @KTamas,
I am sure this is not popping up every day.  However, to solve your problem just click on the "Give a ⭐ on GitHub" once and you will never see that message again. You know that I can't check if you really stared the project on GitHub 😉.
Another option as you already mentioned would be to fork the project and remove the two lines of code.

best regards,
Tim

**Comment by KTamas** [comment]
No, it really did pop up every day! I don't know how or why. I did click it so I guess it's solved now.

**Comment by Dgamblin01** [comment]
_dono_
