### ISSUE TITLE
any way to get intellisense on template files (not yaml)?

### ISSUE THREAD

**Issue by horacimacias** [tim-koehler/Helm-Intellisense#65]
this extension looks great, but I'm trying to get intellisense and highlighting when writing template files, in addition to yaml files.
Is there any way to get intellisense and/or syntax highlighting there?

**Comment by krokofant** [comment]
I have the kubernetes extension installed along this and I'm using the file association to make it work

You can add this to your settings:
```json
    "files.associations": {
      "**/templates/*.tpl": "helm"
    },
```

**Comment by horacimacias** [comment]
thanks!
